name: "Continuous Integration"

env:
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  pull_request:
    branches:
      - "main"
      - "dev"
  push:
    branches:
      - "main"
      - "dev"

jobs:
  run-contracts-integration:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install the dependencies"
        run: "yarn install --immutable"

      - name: "Lint the code"
        run: "yarn lint"

      - name: "Compile the contracts"
        run: "yarn compile"

      - name: "Generate the TypeChain bindings"
        run: "yarn typechain"

      - name: "Test the contracts and generate the coverage report"
        run: "yarn coverage"

      - name: "Send report to Coveralls"
        uses: "coverallsapp/github-action@master"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./coverage/lcov.info"